### ISSUE TITLE
Sayfanın cache'lenmesi sorunun çözülmesi

### ISSUE THREAD

**Issue by Blind-Striker** [CodeFiction/codefiction-tech#14]
Şu an html tarafında yaptığımız bir değişikliğin görünmesi için browser'a ctrl+f5 yapmamız gerekiyor.

**Comment by msusur** [comment]
@Blind-Striker Cloudfront ve AWS'e gecince bu sorun da cozuldu sanirim. Simdilik kapatiyorum olmazsa yine acariz.
