### ISSUE TITLE
patreon destekcilerinin listelenmesi

### ISSUE THREAD

**Issue by ozgend** [CodeFiction/codefiction-tech#25]
patreon api bilgileri public olarak sunmuyor. apikey-apisecret alindiktan sonra incelenecek.

ek0:
https://api.patreon.com/user/5540197

ek1:
https://github.com/oxguy3/patreon-api

ek2:
https://patreon.zendesk.com/hc/en-us/articles/206525646-Does-Patreon-have-an-API

ek3:
https://github.com/Patreon/patreon-js
https://github.com/Patreon/patreon-php

**Comment by msusur** [comment]
fixed with  #24
