### ISSUE TITLE
Jquery not found

### ISSUE THREAD

**Issue by mahmut-gundogdu** [CodeFiction/codefiction-tech#29]
![image](https://user-images.githubusercontent.com/2217899/28260085-21a86590-6ae2-11e7-900d-0406e50cd33b.png)

**Comment by msusur** [comment]
e nerden bulsun hakli tabi, kaldirdik onu :) tesekkurler @mahmut-gundogdu 👍

**Comment by msusur** [comment]
#31 ile @ozgend bunu cozmus. Kapatiyorum. Tesekkurler @mahmut-gundogdu !
